version: '3.8'

services:
  worm-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Named volume keeps data persistent, simulating an external secure store
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      # Azure connection string
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=workstorageleg01;AccountKey=JGpZmZaLU6DoKE8EnCoqzXIIiQQIJQxDPsecbWjzrKOexQMGzNmaPMpzqeA3Gdc88++NP+Rb7Bxb+AStlVrUkQ==;EndpointSuffix=core.windows.net
volumes:
  worm-data: